#!/usr/bin/env bash

set -euox pipefail

# Neovim
sudo dnf install -y neovim python2-neovim python3-neovim

# Dein
DEIN_DIR="$HOME/.dein"

curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > /tmp/install_dein.sh

sh /tmp/install_dein.sh $DEIN_DIR

mkdir -p $HOME/.config/nvim
ln -f -s $(realpath init.vim) $HOME/.config/nvim

nvim -c 'call dein#install() | exit'
